# Generated by Django 3.2.3 on 2021-05-31 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210526_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09123456789'. Only 11 digits allowed.", regex='^\\+?09?\\d{10}$')]),
        ),
    ]
