# Generated by Django 3.2.3 on 2021-06-05 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inferences.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='COVIDCTInference',
            fields=[
                ('HIS_case_id', models.CharField(blank=True, max_length=64, null=True)),
                ('HIS_patient_id', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=inferences.models.COVIDCT_file_path)),
                ('diagnosis', models.CharField(choices=[('NRML', 'Normal'), ('CVID', 'Covid19'), ('ABNR', 'Abnormal'), ('OTHR', 'Other'), ('UNKN', 'Unknown')], default='UNKN', max_length=4)),
                ('report', models.CharField(blank=True, max_length=1024, null=True)),
                ('prescriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChestXRayInference',
            fields=[
                ('HIS_case_id', models.CharField(blank=True, max_length=64, null=True)),
                ('HIS_patient_id', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(choices=[('NRML', 'Normal'), ('ATEL', 'Atelectasis'), ('CARD', 'Cardiomegaly'), ('EFFU', 'Effusion'), ('INFL', 'Infiltration'), ('MASS', 'Mass'), ('NODL', 'Nodule'), ('PNMN', 'Pneumonia'), ('PNTH', 'Pneumothorax'), ('CONS', 'Consolidation'), ('EDMA', 'Edema'), ('EMPH', 'Emphysema'), ('FIBR', 'Fibrosis'), ('PLTK', 'PleuralThickening'), ('HERN', 'Hernia'), ('OTHR', 'Other'), ('UNKN', 'Unknown')], default='UNKN', max_length=4)),
                ('report', models.CharField(blank=True, max_length=1024, null=True)),
                ('prescriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
