# Generated by Django 3.2.3 on 2021-06-06 14:37

import django.core.validators
from django.db import migrations, models
import inferences.models
import inferences.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0002_alter_covidctinference_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chestxrayinference',
            old_name='HIS_case_id',
            new_name='case_id',
        ),
        migrations.RenameField(
            model_name='chestxrayinference',
            old_name='HIS_patient_id',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='covidctinference',
            old_name='HIS_case_id',
            new_name='case_id',
        ),
        migrations.RenameField(
            model_name='covidctinference',
            old_name='HIS_patient_id',
            new_name='patient_id',
        ),
        migrations.AddField(
            model_name='chestxrayinference',
            name='patient_birthday',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chestxrayinference',
            name='patient_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='covidctinference',
            name='patient_birthday',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='covidctinference',
            name='patient_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='covidctinference',
            name='file',
            field=models.FileField(upload_to=inferences.models.COVIDCT_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dcm']), inferences.validators.validate_file_size]),
        ),
    ]
