# Generated by Django 3.2.3 on 2021-06-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0004_auto_20210606_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chestxrayinference',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='chestxrayinference',
            name='patient_birthday',
        ),
        migrations.RemoveField(
            model_name='covidctinference',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='covidctinference',
            name='patient_birthday',
        ),
        migrations.AddField(
            model_name='chestxrayinference',
            name='patient_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidctinference',
            name='patient_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
