# Generated by Django 3.2.3 on 2021-06-14 16:07

import django.core.validators
from django.db import migrations, models
import inferences.models
import inferences.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0006_alter_covidctinference_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidctinference',
            name='file',
            field=models.FileField(upload_to=inferences.models.COVIDCT_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip']), inferences.validators.validate_file_size]),
        ),
    ]
